export const storeData = {
  "stores": [
      {
        "address": {
          "street": "2196 W Park Court",
          "city": "Stone Mountain",
          "state": "MN",
          "zip_code": "30087"
        },
        "departments": false,
        "gps": {
          "latitude": "33.811038",
          "longitude": "-84.131682"
        },
        "name": "Dollar General",
        "retail_store_events": [
          {
            "ID": 1513,
            "post_author": "1",
            "post_date": "2019-06-11 16:07:45",
            "post_date_gmt": "2019-06-11 21:07:45",
            "post_content": "",
            "post_title": "06112019 DG - BASE",
            "post_excerpt": "",
            "post_status": "publish",
            "comment_status": "closed",
            "ping_status": "closed",
            "post_password": "",
            "post_name": "06112019-dg-base",
            "to_ping": "",
            "pinged": "",
            "post_modified": "2019-07-03 14:14:07",
            "post_modified_gmt": "2019-07-03 19:14:07",
            "post_content_filtered": "",
            "post_parent": 0,
            "guid": "https://circular-qa.purered.net/events/06112019-dg-base/",
            "menu_order": 0,
            "post_type": "event",
            "post_mime_type": "",
            "comment_count": "0",
            "filter": "raw"
          }
        ],
        "services": "",
        "store": {
          "ID": 1512,
          "post_author": "1",
          "post_date": "2019-06-11 15:50:50",
          "post_date_gmt": "2019-06-11 20:50:50",
          "post_content": "",
          "post_title": "Dollar General #1234",
          "post_excerpt": "",
          "post_status": "publish",
          "comment_status": "closed",
          "ping_status": "closed",
          "post_password": "",
          "post_name": "dg-1234",
          "to_ping": "",
          "pinged": "",
          "post_modified": "2019-06-11 16:26:29",
          "post_modified_gmt": "2019-06-11 21:26:29",
          "post_content_filtered": "",
          "post_parent": 0,
          "guid": "https://circular-qa.purered.net/?post_type=retail_store&#038;p=1512",
          "menu_order": 0,
          "post_type": "retail_store",
          "post_mime_type": "",
          "comment_count": "0",
          "filter": "raw"
        },
        "store_number": "616"
      },
      {
        "address": {
          "street": "1310 University Avenue",
          "city": "Crookston",
          "state": "MN",
          "zip_code": "56716"
        },
        "departments": false,
        "gps": {
          "latitude": "40.591629",
          "longitude": "-98.365087"
        },
        "name": "Dollar General",
        "retail_store_events": [
          {
            "ID": 1513,
            "post_author": "1",
            "post_date": "2019-06-11 16:07:45",
            "post_date_gmt": "2019-06-11 21:07:45",
            "post_content": "",
            "post_title": "06112019 DG - BASE",
            "post_excerpt": "",
            "post_status": "publish",
            "comment_status": "closed",
            "ping_status": "closed",
            "post_password": "",
            "post_name": "06112019-dg-base",
            "to_ping": "",
            "pinged": "",
            "post_modified": "2019-07-03 14:14:07",
            "post_modified_gmt": "2019-07-03 19:14:07",
            "post_content_filtered": "",
            "post_parent": 0,
            "guid": "https://circular-qa.purered.net/events/06112019-dg-base/",
            "menu_order": 0,
            "post_type": "event",
            "post_mime_type": "",
            "comment_count": "0",
            "filter": "raw"
          }
        ],
        "services": "",
        "store": {
          "ID": 1622,
          "post_author": "1",
          "post_date": "2019-06-13 13:58:12",
          "post_date_gmt": "2019-06-13 18:58:12",
          "post_content": "",
          "post_title": "Dollar General #2345",
          "post_excerpt": "",
          "post_status": "publish",
          "comment_status": "closed",
          "ping_status": "closed",
          "post_password": "",
          "post_name": "dollar-general-2345",
          "to_ping": "",
          "pinged": "",
          "post_modified": "2019-06-13 13:58:12",
          "post_modified_gmt": "2019-06-13 18:58:12",
          "post_content_filtered": "",
          "post_parent": 0,
          "guid": "https://circular-qa.purered.net/?post_type=retail_store&#038;p=1622",
          "menu_order": 0,
          "post_type": "retail_store",
          "post_mime_type": "",
          "comment_count": "0",
          "filter": "raw"
        },
        "store_number": "2345"
      },
      {
        "address": {
          "street": "1925 13th Avenue North",
          "city": "Grand Forks",
          "state": "ND",
          "zip_code": "58203"
        },
        "departments": false,
        "gps": {
          "latitude": "47.93217",
          "longitude": "-97.054545"
        },
        "name": "Dollar General",
        "retail_store_events": [
          {
            "ID": 3,
            "post_author": "1",
            "post_date": "2019-06-11 16:07:45",
            "post_date_gmt": "2019-06-11 21:07:45",
            "post_content": "",
            "post_title": "06112019 DG - BASE",
            "post_excerpt": "",
            "post_status": "publish",
            "comment_status": "closed",
            "ping_status": "closed",
            "post_password": "",
            "post_name": "06112019-dg-base",
            "to_ping": "",
            "pinged": "",
            "post_modified": "2019-07-03 14:14:07",
            "post_modified_gmt": "2019-07-03 19:14:07",
            "post_content_filtered": "",
            "post_parent": 0,
            "guid": "https://circular-qa.purered.net/events/06112019-dg-base/",
            "menu_order": 0,
            "post_type": "event",
            "post_mime_type": "",
            "comment_count": "0",
            "filter": "raw"
          }
        ],
        "services": "",
        "store": {
          "ID": 3,
          "post_author": "1",
          "post_date": "2019-06-13 13:58:12",
          "post_date_gmt": "2019-06-13 18:58:12",
          "post_content": "",
          "post_title": "Dollar General #2345",
          "post_excerpt": "",
          "post_status": "publish",
          "comment_status": "closed",
          "ping_status": "closed",
          "post_password": "",
          "post_name": "dollar-general-2345",
          "to_ping": "",
          "pinged": "",
          "post_modified": "2019-06-13 13:58:12",
          "post_modified_gmt": "2019-06-13 18:58:12",
          "post_content_filtered": "",
          "post_parent": 0,
          "guid": "https://circular-qa.purered.net/?post_type=retail_store&#038;p=1622",
          "menu_order": 0,
          "post_type": "retail_store",
          "post_mime_type": "",
          "comment_count": "0",
          "filter": "raw"
        },
        "store_number": "3"
      },
      {
        "address": {
          "street": "1631 Washington Street",
          "city": "Grand Forks",
          "state": "ND",
          "zip_code": "58201"
        },
        "departments": false,
        "gps": {
          "latitude": "44.394885",
          "longitude": "-89.806212"
        },
        "name": "Dollar General",
        "retail_store_events": [
          {
            "ID": 2,
            "post_author": "1",
            "post_date": "2019-06-11 16:07:45",
            "post_date_gmt": "2019-06-11 21:07:45",
            "post_content": "",
            "post_title": "06112019 DG - BASE",
            "post_excerpt": "",
            "post_status": "publish",
            "comment_status": "closed",
            "ping_status": "closed",
            "post_password": "",
            "post_name": "06112019-dg-base",
            "to_ping": "",
            "pinged": "",
            "post_modified": "2019-07-03 14:14:07",
            "post_modified_gmt": "2019-07-03 19:14:07",
            "post_content_filtered": "",
            "post_parent": 0,
            "guid": "https://circular-qa.purered.net/events/06112019-dg-base/",
            "menu_order": 0,
            "post_type": "event",
            "post_mime_type": "",
            "comment_count": "0",
            "filter": "raw"
          }
        ],
        "services": "",
        "store": {
          "ID": 2,
          "post_author": "1",
          "post_date": "2019-06-13 13:58:12",
          "post_date_gmt": "2019-06-13 18:58:12",
          "post_content": "",
          "post_title": "Dollar General #2345",
          "post_excerpt": "",
          "post_status": "publish",
          "comment_status": "closed",
          "ping_status": "closed",
          "post_password": "",
          "post_name": "dollar-general-2345",
          "to_ping": "",
          "pinged": "",
          "post_modified": "2019-06-13 13:58:12",
          "post_modified_gmt": "2019-06-13 18:58:12",
          "post_content_filtered": "",
          "post_parent": 0,
          "guid": "https://circular-qa.purered.net/?post_type=retail_store&#038;p=1622",
          "menu_order": 0,
          "post_type": "retail_store",
          "post_mime_type": "",
          "comment_count": "0",
          "filter": "raw"
        },
        "store_number": "2"
      },
      {
        "address": {
          "street": "1631 Washington Street",
          "city": "Grand Forks",
          "state": "ND",
          "zip_code": "58201"
        },
        "departments": false,
        "gps": {
          "latitude": "44.394885",
          "longitude": "-89.806212"
        },
        "name": "Dollar General",
        "retail_store_events": [
          {
            "ID": 2,
            "post_author": "1",
            "post_date": "2019-06-11 16:07:45",
            "post_date_gmt": "2019-06-11 21:07:45",
            "post_content": "",
            "post_title": "06112019 DG - BASE",
            "post_excerpt": "",
            "post_status": "publish",
            "comment_status": "closed",
            "ping_status": "closed",
            "post_password": "",
            "post_name": "06112019-dg-base",
            "to_ping": "",
            "pinged": "",
            "post_modified": "2019-07-03 14:14:07",
            "post_modified_gmt": "2019-07-03 19:14:07",
            "post_content_filtered": "",
            "post_parent": 0,
            "guid": "https://circular-qa.purered.net/events/06112019-dg-base/",
            "menu_order": 0,
            "post_type": "event",
            "post_mime_type": "",
            "comment_count": "0",
            "filter": "raw"
          }
        ],
        "services": "",
        "store": {
          "ID": 2,
          "post_author": "1",
          "post_date": "2019-06-13 13:58:12",
          "post_date_gmt": "2019-06-13 18:58:12",
          "post_content": "",
          "post_title": "Dollar General #2345",
          "post_excerpt": "",
          "post_status": "publish",
          "comment_status": "closed",
          "ping_status": "closed",
          "post_password": "",
          "post_name": "dollar-general-2345",
          "to_ping": "",
          "pinged": "",
          "post_modified": "2019-06-13 13:58:12",
          "post_modified_gmt": "2019-06-13 18:58:12",
          "post_content_filtered": "",
          "post_parent": 0,
          "guid": "https://circular-qa.purered.net/?post_type=retail_store&#038;p=1622",
          "menu_order": 0,
          "post_type": "retail_store",
          "post_mime_type": "",
          "comment_count": "0",
          "filter": "raw"
        },
        "store_number": "6"
      },
      {
        "address": {
          "street": "1631 Washington Street",
          "city": "Grand Forks",
          "state": "ND",
          "zip_code": "58201"
        },
        "departments": false,
        "gps": {
          "latitude": "44.394885",
          "longitude": "-89.806212"
        },
        "name": "Dollar General",
        "retail_store_events": [
          {
            "ID": 2,
            "post_author": "1",
            "post_date": "2019-06-11 16:07:45",
            "post_date_gmt": "2019-06-11 21:07:45",
            "post_content": "",
            "post_title": "06112019 DG - BASE",
            "post_excerpt": "",
            "post_status": "publish",
            "comment_status": "closed",
            "ping_status": "closed",
            "post_password": "",
            "post_name": "06112019-dg-base",
            "to_ping": "",
            "pinged": "",
            "post_modified": "2019-07-03 14:14:07",
            "post_modified_gmt": "2019-07-03 19:14:07",
            "post_content_filtered": "",
            "post_parent": 0,
            "guid": "https://circular-qa.purered.net/events/06112019-dg-base/",
            "menu_order": 0,
            "post_type": "event",
            "post_mime_type": "",
            "comment_count": "0",
            "filter": "raw"
          }
        ],
        "services": "",
        "store": {
          "ID": 2,
          "post_author": "1",
          "post_date": "2019-06-13 13:58:12",
          "post_date_gmt": "2019-06-13 18:58:12",
          "post_content": "",
          "post_title": "Dollar General #2345",
          "post_excerpt": "",
          "post_status": "publish",
          "comment_status": "closed",
          "ping_status": "closed",
          "post_password": "",
          "post_name": "dollar-general-2345",
          "to_ping": "",
          "pinged": "",
          "post_modified": "2019-06-13 13:58:12",
          "post_modified_gmt": "2019-06-13 18:58:12",
          "post_content_filtered": "",
          "post_parent": 0,
          "guid": "https://circular-qa.purered.net/?post_type=retail_store&#038;p=1622",
          "menu_order": 0,
          "post_type": "retail_store",
          "post_mime_type": "",
          "comment_count": "0",
          "filter": "raw"
        },
        "store_number": "5"
      }
    ]
}