export const categoryImages = {
    Grocery: "grocery",
    Meat: "Hugos_dc_dept_meat",
    Produce: "produce",
    Seafood: "seafood",
    Deli: "deli",
    Bakery: "bakery",
    Dairy: "dairy",
    Frozen: "frozen-foods",
    "Home & Family": "health-personal-care",
    Floral: "floral",
    "Naturally Organic" : "natural-208x300",
    "Wine & Spirits": "wine_spirits-208x300",
    "Wine & Spirits ": "wine_spirits-208x300",
}